package com.mdung.entities;
// Generated Apr 10, 2023, 10:48:36 AM by Hibernate Tools 4.3.6.Final


import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.UniqueConstraint;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Data;

/**
 * Account generated by hbm2java
 */

@Data
@Entity
@Table(name = "account", catalog = "qlmyweb", uniqueConstraints = @UniqueConstraint(columnNames = "Username"))
public class Account implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Integer id;
	@NotBlank
	@Column(name = "Username")
	private String username;
	@Column(name = "Password")
	@NotBlank
	@Size(min=6,max=12,message = "Password must be between 6-12 characters")
	private String password;
	@Column(name = "Fullname")
	@NotBlank
	private String fullname;
	@Column(name = "Email")
	@Email(message = "Email invalidate")
	@NotBlank
	private String email;
	@Column(name = "Role")
	private Boolean role;

}
