package com.mdung.entities;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;

// Generated Apr 10, 2023, 10:48:36 AM by Hibernate Tools 4.3.6.Final

/**
 * Danhmuc generated by hbm2java
 */
@Data
@Entity
@Table(name = "danhmuc", catalog = "qlmyweb")
public class Danhmuc implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@Column(name = "tendanhmuc", length = 45)
	private String tendanhmuc;
	@Column(name = "mota", length = 50)
	private String mota;

}
