package com.mdung.entities;

import java.util.Date;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;
import jakarta.persistence.Table;
import lombok.Data;

// Generated Apr 10, 2023, 10:48:36 AM by Hibernate Tools 4.3.6.Final

/**
 * Danhmuc generated by hbm2java
 */
@Data
@Entity
@Table(name = "orders", catalog = "qlmyweb")
public class Orders implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Integer id;
	@OneToOne
	@JoinColumn(name = "user",nullable = true)
	private Account user;
	@Column(name = "createdate")
	private Date createdate;
	@Column(name = "address",nullable = true)
	private String address;
	@Column(name = "phonenumber",nullable = true)
	private String phonenumber;
	@Column(name = "status")
	private boolean status;

}
