package com.mdung.entities;
// Generated Apr 10, 2023, 10:48:36 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.validation.constraints.DecimalMax;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * Product generated by hbm2java
 */
@Data
@Entity
@Table(name = "product", catalog = "qlmyweb")
public class Product implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "ID", unique = true, nullable = false)
	private Integer id;
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "danhmuc")
	private Danhmuc category;
	@Column(name = "name", length = 45)
	private String name;
	@Column(name = "gia", length = 10)
	private Double price;
	@Column(name = "ngaytao")
	private Date datecreated;
	@Column(name = "tinhtrang")
	private Boolean status;
	@Column(name = "mota", length = 1000)
	private String description;
	@Column(name = "hinhanh")
	private String image;
	@Column(name = "soluong")
	private int quantity;

}
