package com.mdung.entities;
// Generated Apr 10, 2023, 10:48:36 AM by Hibernate Tools 4.3.6.Final

import java.util.Date;

import org.springframework.web.multipart.MultipartFile;

import jakarta.persistence.Column;
import jakarta.validation.constraints.DecimalMin;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;

/**
 * Product generated by hbm2java
 */
@Data
public class ProductSaveFile {
	@NotNull
	private Integer id;

	private Danhmuc category;
	@NotBlank
	private String name;
	@NotNull
	@DecimalMin("0")
	private Double price;

	private Date datecreated;

	private Boolean status;
	@NotBlank
	private String description;

	private MultipartFile image;
	private int quantity;
}
